<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="The home of Mitch Andrews!" name="description">
    <meta content="wobbier, mitchell andrews, coding, programmer, video game programmer, student, indie" name="keywords">
    <title>{{title}}</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link href="/css/theme.css" rel="stylesheet" type="text/css">{{#customCover}}
    <link href="/css/{{slug}}.css" rel="stylesheet" type="text/css">{{/customCover}}
    <script src="http://code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <meta content="-xwR0iZlTA0I0eiL4y5ZNaQib2lM1gIgqBXCBdgXvmQ" name="google-site-verification">
</head>

<body>
    <div class="wrapper">
        <div id="header">
            <div id="logo">
                <img src="/img/wobbier-logo.png">
            </div>
            <div id="nav">
                <ul>
                    <li class="right">
                        <a href="/blog">
                            <img src="/img/blog.png">
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <img src="/img/home.png">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="clearfix">