		<div class='content home' id="home">
			<div class="block top left"></div>
			<div class="block bottom left"></div>
			<div class="block top right"></div>
			<div class="block bottom right"></div>
			<p>My name is Mitchell Andrews and I'm a <strong>{{age}}</strong> year old game programmer from <strong>Toronto</strong>.</p>
			<p>I program primarily in <strong>C++</strong>, <strong>C#</strong>, and <strong>Node.js</strong>.</p>
		</div>